### ISSUE TITLE
Column mapping is missing

### ISSUE THREAD

**Issue by bogdanovd89** [tiagoln/EntityFramework.BulkExtensions#2]
Hello!
Sometimes column order in database and model are different, in this case SqlBulkCopy does not work properly. It tries to insert column A from model to column B in a database.
Localy I've added that mapping:
```
internal static void BulkInsertToTable(this Database context, DataTable dataTable, string tableName,
            SqlBulkCopyOptions sqlBulkCopyOptions)
        {
            using (
                var bulkcopy = new SqlBulkCopy((SqlConnection)context.Connection, sqlBulkCopyOptions,
                    (SqlTransaction)context.CurrentTransaction.UnderlyingTransaction))
            {
                foreach (var dataTableColumn in dataTable.Columns) {
                    bulkcopy.ColumnMappings.Add(dataTableColumn.ToString(), dataTableColumn.ToString());
                }
                bulkcopy.DestinationTableName = tableName;
                bulkcopy.BulkCopyTimeout = context.Connection.ConnectionTimeout;
                bulkcopy.WriteToServer(dataTable);
            }
        }
```

**Comment by tiagoln** [comment]
Hello! Sorry for taking so long to reply, I was too busy at work. I'll fix this problem soon. Thanks for the help.

**Comment by tiagoln** [comment]
I've just committed the proposed solution to the repository, thanks bogdanovd89.

**Comment by bogdanovd89** [comment]
Great, thank you. Are you going to support EF Core version?

**Comment by tiagoln** [comment]
I intend to. The main problem was the reliance on the EntityFramework.MappingAPI to get the database metadata, wich is obsolete for some time and only supports EF6.

I've committed a new code to stop using the MappingAPI. For the next versions, the only dependency necessary will be the EntityFramework. I will be releasing a new beta version on the nuget repository sometime this week with this alterations.

As the library does not rely on the EntityFramework.MappingAPI any more, I plan to extend it for the EFCore in the future.

**Comment by tiagoln** [comment]
I've released a new version, with a new package to support EFCore, check it out :)
